### ISSUE TITLE
FAPro osX

### ISSUE THREAD

**Issue by DirkPersky** [DirkPersky/typo3-rte-ckeditor-fontawesome#11]
At first I tried to incorporate it in my current configuration, which resulted in the error. But removing my config and using yours results in the very same behavior:
Page.TsConfig
```
RTE.default.preset = fa5pro
```
TypoScript 
```
plugin.tx_ckeditor_fontawesome.css = https://pro.fontawesome.com/releases/v5.9.0/css/all.css
```
```
imports:
  - { resource: "EXT:rte_ckeditor/Configuration/RTE/Full.yaml" }
  - { resource: "EXT:rte_ckeditor_fontawesome/Configuration/RTE/PluginFA5Pro.yaml" }
# Add configuration for the editor
editor:
  config:
    # css definitions for the editor
    contentsCss:
      - "EXT:rte_ckeditor/Resources/Public/Css/contents.css"
      - "https://pro.fontawesome.com/releases/v5.9.0/css/all.css"
```

Neither external like above nor internal CSS like `EXT:mysiteext/Resources/Public/Stylesheets/Additional/fontawesome-icons.min.css`works here in 8LTS, both result in the same error. I'd be happy to debug, but I just get the screenshot above, so the  broken 
```html
<td class="cke_dialog_ui_vbox_child" role="presentation"> id="cke_95_uiElement" class="cke_dialog_ui_html" </td>
```

_Originally posted by @jpmschuler in https://github.com/DirkPersky/typo3-rte-ckeditor-fontawesome/issues/8#issuecomment-503142413_
