### ISSUE TITLE
overriding css path in yaml not working

### ISSUE THREAD

**Issue by medarob** [DirkPersky/typo3-rte-ckeditor-fontawesome#38]
I wanted to change the css path to the FontAwesome css file and therefore wanted to changed the value of the url in the yaml file. However, the current value to the cdn isn't overridden, the new value was added.

current: https://use.fontawesome.com/releases/v6.2.0/css/all.css
new: EXT:my_sitepackage/Resources/Public/Plugins/fontawesome/css/all.css

Here are excerpts from the files:

our **RTE_config_custom.yaml** starts with

```
imports:
  - { resource: "EXT:rte_ckeditor/Configuration/RTE/Processing.yaml" }
  - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Base.yaml" }
  - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Plugins.yaml" }
  - { resource: "EXT:rte_ckeditor_fontawesome/Configuration/RTE/PluginFA6.yaml" }
  - { resource: "EXT:my_sitepackage/Configuration/RTE/Partials/custom_styles.yaml" }
```

in **custom_styles.yaml** I wanted to override the current value of 

```
editor:
  config:
    fontAwesome:
      - "https://use.fontawesome.com/releases/v6.2.0/css/all.css"
```
to another url

```
editor:
  config:
    fontAwesome:
      - "EXT:my_sitepackage/Resources/Public/Plugins/fontawesome/css/all2.css"
```

but in the BE two css files were loaded.
For testing purposes I renamed the new `all.css` to `all2.css`, just to see how many times the file was loaded, because it will result in an 404 error.

![grafik](https://github.com/DirkPersky/typo3-rte-ckeditor-fontawesome/assets/33951787/3586b33e-e285-4427-a1a0-2d925c899267)

As you can see, the `all2.css` is referenced two times and I also see the original file (the https link) being referenced two times.
What I expected was that the link is just referenced once and that the current https links shouldn't be available anymore.

Am I doing something wrong or why can't I override the original css link (https://use.fontawesome.com/releases/v6.2.0/css/all.css)?
