### ISSUE TITLE
allowedContent: true really necessary?

### ISSUE THREAD

**Issue by tomhatzer** [DirkPersky/typo3-rte-ckeditor-fontawesome#6]
Hi Dirk!

Thank you very much for this extension.

One quick question: Is `allowedContent: true` here really necessary?

Wouldn't something like this work too?
```
editor:
  config:
    extraAllowedContent:
      - i(*){*}
```

Setting allowedContent to true without handling every input on your own is pretty bad I think... 😅 

Best wishes
Tom
